### ISSUE TITLE
URL in Effect.purs returns 404

### ISSUE THREAD

**Issue by LucianU** [purescript/purescript-effect#10] opened 2018-11-05 10:35 UTC
The file mentioned in the title links to http://www.purescript.org/learn/eff/. That links returns a 404.

**Comment by k4b7** [comment] 2019-01-18 02:59
Should it be linking to https://github.com/purescript/documentation/blob/master/guides/Eff.md?

**Comment by hdgarrood** [comment] 2019-01-18 03:53
That was what that link pointed to originally, but the guide is for Eff, which is of course a bit different from Effect. Anyway, I'm going to close this as a duplicate of #5.

**Closed as completed by hdgarrood** 2019-01-18 03:53 UTC
